services:
  web:
    build: .
    container_name: flask-web
    ports:
      - "8000:5000"
    environment:
      REDIS_HOST: redis 
      REDIS_PORT: 6379
    depends_on:
      - redis 
  redis:
    image: redis:7-alpine
    container_name: redis-db
