name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t flask-app:latest .
  
      - name: List docker images
        run: docker images
